executionOrder:
  flowsOrder:
  - ClickingApplyForEarlyAccessButton
  - ClickingLearnMoreAboutBeaconMoney
  - ClickOnSafeTravelPlans
  - ClickOnLearningHub
  - ClickOnPlanningList
  - ClickOnNewPlanningListButton
  - ClickToViewBeaconMoneyPage
  - ClickToViewFeaturedArticle
